import type { Metadata } from "next";
import globalstyle from "./globals.module.css";
import "./styles/icon-styles.css";
import Link from 'next/link';
import NavLink from "./layouts/navLink";
import { Lato } from 'next/font/google'
import Head from "next/head";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCartShopping, faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import CartCount from "./components/cartcount";

config.autoAddCss = false;
let lib = library.add(faCartShopping, faMagnifyingGlass);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: "400",
  style: "normal",
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en"> 
      <Head>
        <link rel="icon"
          href="/assets/cart-shopping-solid-full"/>
      </Head>
      <body className={`${globalstyle.body} ${lato.className}`}>    
        <nav >
          <ul className={globalstyle.nav}>
          
            <li className={`${globalstyle.navElements}`}>
              <div>
                <NavLink id="home" classlist={`${globalstyle.navAnchorTags}`} destination="/" innerText="Home"/>
              </div>
              
            </li>
            <li className={globalstyle.navElements}>
              <div>
                <NavLink id="profile" classlist={`${globalstyle.navAnchorTags}`} destination="./profile" innerText="Profile"/>
              </div>
              
            </li>
            <li className={globalstyle.navElements}>
              <div>
                 <NavLink id="logout" classlist={`${globalstyle.navAnchorTags}`} destination="./logout" innerText="Logout"/>
              </div>
             
            </li>
            <li className={globalstyle.navElements}>
              <form action="./search" method="get">
                <input type="text" placeholder="Search" />
                <FontAwesomeIcon icon='magnifying-glass' type="submit" className="search-button" />
                {/* <button type="submit" className={globalstyle.searchButton}>
                  
                </button> */}
              </form>
            </li>
            <li className={globalstyle.navElements}>
              {/* <NavLink classlist={`${globalstyle.navAnchorTags}`} destination="./cart" innerText="Cart">
                
              </NavLink> */}
              <div className="cart">
                <FontAwesomeIcon icon='cart-shopping' />
                <CartCount />
              </div>
              
              
              
              
            </li>
          </ul>
        </nav>
        <header></header>
        <main>
          {children}
        </main>
        <footer className={globalstyle.footer}></footer>
      </body>
    </html>
  );
}
