import type { Metadata } from "next";
import globalstyle from "./globals.module.css";
import "./styles/icon-styles.css";
import handleUuid from "./hooks/serverHooks/handleKeyUuid";
import NavLink from "./layouts/navLink";
import SearchBar from "./layouts/searchBar";
import HamburgerBtn from "./layouts/hamburgerBtn";
import { Lato } from 'next/font/google'
import Head from "next/head";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCartShopping, faMagnifyingGlass, faBars } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import CartCount from "./components/cartcount";


config.autoAddCss = false;
let lib = library.add(faCartShopping, faMagnifyingGlass, faBars);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: "400",
  style: "normal",
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  const allNavHeaders:string[] = ["Search", "Cart"];
  // const ulRef = useRef(null);
  return (
    <html lang="en"> 
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon"
          href="/assets/cart-shopping-solid-full"/>
      </Head>
      <body className={`${globalstyle.body} ${lato.className}`}>    
        <nav style={{position:"sticky", top:"0px", zIndex:"0"}}>

          
          
          
          <ul className={globalstyle.globalNav}>

            <HamburgerBtn fontAwesomeHamburger={<FontAwesomeIcon icon='bars' className="hamburger-icon" />}/>
            
            
            {allNavHeaders.map((each:string)=> {
              const lowercaseValue = each.toLowerCase();
              if(lowercaseValue === "search"){
                return (
                  <SearchBar key={handleUuid()} fontAwesome={<FontAwesomeIcon icon='magnifying-glass' className='magnifying-glass' />}/>
                );
              }else if(lowercaseValue === "cart"){
                return (
                <NavLink key={handleUuid()} id={lowercaseValue} classlist={`${globalstyle.navAnchorTags}`} destination={`/${lowercaseValue}`}>
                    <FontAwesomeIcon icon='cart-shopping' />
                    <CartCount /> 
                </NavLink>);
              }
              
            })}
          </ul>
        </nav>

        <header></header>
        <main  className={globalstyle.main}>
          {children}
          
        </main>
        <footer className={globalstyle.footer}></footer>
      </body>
    </html>
  );
}
