import type { Metadata } from "next";
import globalstyle from "./globals.module.css";
import "./styles/icon-styles.css";
import { v7 as uuidv7 } from 'uuid';
import NavLink from "./layouts/navLink";
import SearchBar from "./layouts/searchBar";
import { Lato } from 'next/font/google'
import Head from "next/head";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import { library } from '@fortawesome/fontawesome-svg-core';
import { faCartShopping, faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import CartCount from "./components/cartcount";

config.autoAddCss = false;
let lib = library.add(faCartShopping, faMagnifyingGlass);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lato = Lato({
  weight: "400",
  style: "normal",
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {

  const allNavHeaders:string[] = ["Home","Profile","Messages", "logout", "Search", "Cart"];

  return (
    <html lang="en"> 
      <Head>
        <link rel="icon"
          href="/assets/cart-shopping-solid-full"/>
      </Head>
      <body className={`${globalstyle.body} ${lato.className}`}>    
        <nav >
          <ul className={globalstyle.nav}>

            
            {allNavHeaders.map((each:string)=> {
              const lowercaseValue = each.toLowerCase();
              if(lowercaseValue === "search"){
                return (
                  <SearchBar key={uuidv7()} fontAwesome={<FontAwesomeIcon icon='magnifying-glass' className="magnifying-glass" />}/>
                );
              }else if(lowercaseValue === "cart"){
                return (
                <NavLink key={uuidv7()} id={lowercaseValue} classlist={`${globalstyle.navAnchorTags}`} destination={`/${lowercaseValue}`}>
                    <FontAwesomeIcon icon='cart-shopping' />
                    <CartCount /> 
                </NavLink>);
              }
              
              return (
                  <NavLink key={uuidv7()} id={lowercaseValue} classlist={`${globalstyle.navAnchorTags}`} 
                  destination={lowercaseValue==="home"?"/": `/${lowercaseValue}`} 
                  innerText={each}/>
              );
            })}
          
            {/* <li className={`${globalstyle.navElements}`}>
                <NavLink id="home" classlist={`${globalstyle.navAnchorTags}`} destination="/" innerText="Home"/>
              
              
            </li>
            <li className={globalstyle.navElements}>
              
                <NavLink id="profile" classlist={`${globalstyle.navAnchorTags}`} destination="/profile" innerText="Profile"/>
              
              
            </li>
            <li className={globalstyle.navElements}>          
                 <NavLink id="logout" classlist={`${globalstyle.navAnchorTags}`} destination="/logout" innerText="Logout"/>
            </li>
            <li className={globalstyle.navElements}>
              <form action="/search" method="get" >
              <div className={globalstyle.searchButtonParentDiv}>
                <input type="text" placeholder="Search" name="searchProducts" className={globalstyle.searchButtonInput}/>
                
                <button type="submit" className={globalstyle.searchButton}>
                  <FontAwesomeIcon icon='magnifying-glass' className="magnifying-glass" />
                </button>
              </div>
                
              </form>
            </li>

            <li className={globalstyle.navElements}>
                <NavLink id="logout" classlist={`${globalstyle.navAnchorTags}`} destination="/cart">
                    <FontAwesomeIcon icon='cart-shopping' />
                    <CartCount /> 
                </NavLink>
            </li> */}

          </ul>
        </nav>
        <header></header>
        <main>
          {children}
        </main>
        <footer className={globalstyle.footer}></footer>
      </body>
    </html>
  );
}
